from gtts import gTTS

texto = '''Bem-vindo a outro episódio de "Tailscale Explicado", eu sou Alex. Esta é a playlist onde contamos tudo o que você sempre quis saber sobre o Tailscale, coisas como roteadores de sub-rede, SSH do Tailscale e ACLs. No vídeo de hoje, vamos falar sobre nós de saída (exit nodes). Agora, o que é um nó de saída? Bem, de forma simples, é uma maneira de você direcionar todo o tráfego do seu dispositivo cliente, como um telefone ou laptop, e fazê-lo sair para a internet pública via Tailscale em um ponto geográfico específico da internet. 

Digamos que você queira fazer algum banco online enquanto está de férias. Isso aconteceu comigo neste verão, eu queria acessar minha conta bancária nos EUA enquanto estava na Inglaterra. No entanto, meu banco decidiu que acessar o aplicativo bancário de outro país era um grande risco de segurança. Então, o que eu fiz foi ativar a funcionalidade de nó de saída para que meu telefone enviasse todo o seu tráfego através do Tailscale como um nó de saída para esta casa aqui na Carolina do Norte. De repente, meu banco não tinha ideia de que meu tráfego era diferente do que seria se eu estivesse fisicamente neste prédio.

Você pode estar familiarizado com esse conceito a partir de VPNs de privacidade mais tradicionais, como a MOLVAD, com quem temos uma parceria, aliás. Essas VPNs de privacidade são muito boas em fazer você parecer estar em uma localização geográfica diferente por todos os tipos de razões interessantes. Mas o Tailscale é muito mais do que isso. Sim, você pode fazer isso também e emular essa funcionalidade com nós de saída. Mas o Tailscale é ótimo para empresas e auto-hospedagem. Então, vamos mergulhar nos nós de saída.

Por padrão, o Tailscale age como uma rede de sobreposição (overlay network). Ele só roteia o tráfego entre dispositivos que executam o Tailscale e não toca no seu tráfego de internet pública, como quando você visita o Google ou o Hacker News, por exemplo. A configuração de rede de sobreposição é ideal para a maioria das pessoas que precisam de comunicação segura entre dispositivos sensíveis, como servidores de empresas ou computadores domésticos, mas não precisam ou querem as camadas extras de criptografia ou latência para sua conexão com a internet pública.

Mas e se você estiver em uma rede Wi-Fi não confiável, como uma cafeteria ou talvez algo em um aeroporto? Ou talvez você queira ter uma maneira de testar rapidamente a visão de mundo de diferentes redes para ver se é a sua implementação local de DNS que está causando problemas. É aí que um nó de saída realmente se torna útil.

Configurar um é simples. Muitos dispositivos podem ser usados como nós de saída, desde um sistema Linux até um computador Windows ou Mac, ou até mesmo uma Apple TV. Sim, realmente uma Apple TV. Se você estiver executando um firewall DIY como o OpenSense, você pode até instalar o Tailscale diretamente lá e usar esse único dispositivo que presumivelmente já está ligado o tempo todo em sua rede como um nó de saída e roteador de sub-rede também. Aqui está um card para o vídeo do Tailscale que explica os roteadores de sub-rede para você.

O tipo de dispositivo que você escolhe como nó de saída não importa muito. Todos eles provavelmente serão rápidos o suficiente e limitados pela velocidade da sua internet no local do nó de saída em si. Mas minha escolha pessoal para um dispositivo de baixo consumo que está sempre ligado e que você poderia pedir a um amigo ou parente para hospedar com pouco ou nenhum custo seria algo como uma Apple TV, que consome menos de um watt no modo de espera e, sim, a funcionalidade de nó de saída e roteamento de sub-rede ainda funciona nesse estado de baixo consumo, ou o humilde Raspberry Pi.

Você também pode considerar executar o Tailscale em um VPS na nuvem em algum lugar como Hetzner ou Linode. Você pode fazer isso para usá-lo como uma maneira fácil de escolher uma localização geográfica diferente para o seu tráfego. No entanto, isso vem com uma desvantagem potencial. Tráfego de nível de consumidor rotineiro, como navegação via um bloco de IP de data center, porque lembre-se de que você agora parecerá estar dentro desse data center, é que captchas e coisas que não estão acostumadas a ver esse tipo de tráfego de um bloco IP comercial ficarão um pouco irritadas com você. Então, você é muito mais propenso a receber aqueles quebra-cabeças irritantes se fizer isso a longo prazo.

No Linux, ativar a funcionalidade de nó de saída é tão simples quanto um comando `tailscale set --advertise-exit-node` no CLI. No Mac e no Windows, você pode simplesmente selecionar para permitir que este nó atue como um nó de saída nas configurações do cliente. Agora, você precisará aprovar manualmente cada nó que solicitar essa funcionalidade no seu console de administração do Tailscale. Isso leva apenas alguns cliques, mas se você quiser, podemos configurar regras de ACL para aprovar automaticamente solicitações de nós de saída usando os recursos de aprovadores automáticos em suas ACLs. Vou colocar um trecho na tela agora e, como você pode ver, são apenas algumas linhas de código que você cola no seu console de administração. O aprovador automático de um nó de saída pode ser o endereço de e-mail completo de login de um usuário, um nome de grupo, um grupo automático ou um proprietário de tag. Uma vez configurado, sempre que você ativar a funcionalidade de nó de saída, ela será automaticamente aprovada em sua tailnet.

Uma última configuração que gostaria de mencionar é a configuração "Permitir acesso à LAN". Ativar isso permitirá o acesso direto à sua rede local ao rotear o tráfego através de um nó de saída. Em outras palavras, a rede à qual o nó de saída está fisicamente conectado não será acessível por clientes que usam esse nó de saída, a menos que você habilite esse recurso. É muito a mesma ideia de um roteador de sub-rede, apenas com um controle um pouco menos refinado. Se você quiser ser explícito sobre o que é ou não permitido, então você deve ativar o roteamento de sub-rede para os intervalos de sub-rede específicos que você está interessado.

Agora, antes de terminarmos, algumas ressalvas. No Android, MacOS e Windows, o recurso de nó de saída ainda está passando por otimizações de desempenho, pois é executado no espaço do usuário. Se você quiser a melhor experiência absoluta, recomendamos que você use Linux. Pode ser como uma VM ou naquele Raspberry Pi que está em uma de suas gavetas e que você jurou que um dia encontraria um caso de uso perfeito para ele. Bem, este pode muito bem ser ele.

Então, acho que isso cobre os nós de saída. Não se esqueça de verificar os links na descrição abaixo para todas as nossas transmissões ao vivo e todas as outras playlists do Tailscale Explicado. Como sempre, muito obrigado por assistir e até a próxima vez, eu sou Alex do Tailscale.'''

tts = gTTS(texto, lang="pt")
tts.save("saida.mp3")
print("Arquivo de áudio salvo como saida.mp3")